### ISSUE TITLE
getYearsAsINDEX

### ISSUE THREAD

**Issue by matteodefelice** [SantanderMetGroup/transformeR#12]
I am loading a NetCDF with loadGridData, it contains ERA-IN daily data. I wanted to use `getYearsAsINDEX` to deal with the annoying DJF subsetting but the function just returns the actyal year without `correcting` anything. The same if before I subset the file selecting the months `c(12, 1, 2)`. Is it a bug or I'm doing something wrong?

**Comment by jbedia** [comment]
Hi Matteo,
To my knowledge `getYearsAsINDEX` is working fine. I use it very often. You can run this example to check it:
```R
library(transformeR)
data("EOBS_Iberia_tas")
getSeason(EOBS_Iberia_tas)
## [1] 12  1  2
range(getRefDates(EOBS_Iberia_tas))
## [1] "1982-12-01 00:00:00 GMT" "2002-02-28 00:00:00 GMT"
range(getYearsAsINDEX(EOBS_Iberia_tas))
## [1] 1983 2002
```

Is it possible that the dates of your netCDF are not being correctly interpreted for some reason?
cheers

**Comment by matteodefelice** [comment]
Thanks Joaquin for the answer, I have already tried the example code and it worked. Currently, I'm just a bit confused on the expected output of this function. Now, if I run the following code: 
```
f = loadGridData('/my/path/tp-europe-011979-062017.nc', var = 'tp', years = 2000:2010, season = c(12, 1, 2))
[2017-09-04 15:44:05] Defining geo-location parameters
[2017-09-04 15:44:05] Defining time selection parameters
[2017-09-04 15:44:05] Retrieving data subset ...
[2017-09-04 15:44:08] Done
> getSeason(f)
[1] 12  1  2
> range(getRefDates(f))
[1] "1999-12-01 00:00:00 GMT" "2010-02-28 12:00:00 GMT"
> 
> range(getYearsAsINDEX(f))
[1] 2000 2010
```
Ok, but if I don't subset the season or if instead of `c(12, 1, 2)` I use `c(1, 2, 12)` I have the year identical to "year as index". Ok, so the function works only when the season is between two years? The documentation is not clear on this point, what do you think?

**Comment by jbedia** [comment]
Hi Matteo, Yes, this is the expected behaviour. The only difference between the "raw" years, as directly extracted with `getRefDates`, for instance, and the years returned by `getYearsAsINDEX`, lies in the value returned for **year-crossing seasons**, for the reason you already know. Note however that `season = c(1,2,12)` is not the same as `season = c(12,1,2)` (order matters). Seasons should always encompass sets of contiguous months, or at least that is what I would recommend in order to avoid unexpected results... This is explained in the argument `season` of the loading functions. If you feel some parts of the documentation need to be improved (I am sure some can be better explained), I will be more than happy of receiving your suggestions.

**Comment by matteodefelice** [comment]
Thanks for the answer, we can close this issue and I will surely suggest any improvement in the docs in the future!

**Comment by matteodefelice** [comment]
Sorry, I reopen the issue just to ask you a clarification: what if I want to compute the annual averages considering the hydrological year (oct to september)? Does getYearsAsINDEX work as for DJF?

**Comment by matteodefelice** [comment]
Great, thanks!
