### ISSUE TITLE
Metadata rad2cc function

### ISSUE THREAD

**Issue by dmbettin** [SantanderMetGroup/transformeR#20]
Hi @jbedia , 

I think there is an error in the function mentioned in the subject because after applying it the "clt$InitializationDates" only have "Member_1". I made the calculation using as input rtds, I haven´t tried using rsds and rlds.

Thank you!
Best regards!

**Comment by jbedia** [comment]
Hi @dmbettin, thanks for reporting. Could you send a reproducible example? Best regards

**Comment by dmbettin** [comment]
This is the data I am using: https://drive.google.com/open?id=1aa_f2SgWpE-JIW7fFf2PKXYq8RAg8t9N
Then I applied:
` data.bc.cross$rtds$Data <- data.bc.cross$rtds$Data/0.00864`
` data.bc.cross$rtds <- setGridUnits(data.bc.cross$rtds, "W.m-2")`
`  clt <- rad2cc(rtds = data.bc.cross$rtds)`

You can see in the metafile ("$rtds$InitializationDates") that "data.bc.cross" has 15 names of members from 1-15, but clt has only one name "Member_1" repeated 15 times.

**Comment by jbedia** [comment]
Hi @dmbettin, thanks for the example data. The problem lies in the definition of dimensions in the input object. At some point during the process the singleton dimension "loc" is lost. This is needed in order to the function to understand that you are working on one single location. 

```R
library(convertR)
data.bc.cross$rtds$Data <- data.bc.cross$rtds$Data/0.00864
data.bc.cross$rtds <- setGridUnits(data.bc.cross$rtds, "W.m-2")
```
For instance, it can be easily recovered using the internal helper `redim`:
```R
data.bc.cross$rtds <- redim(data.bc.cross$rtds, loc = TRUE)
```
Now, it works:
```R
clt <- rad2cc(rtds = data.bc.cross$rtds)
getShape(clt) 

## member   time    lat    lon 
##     15   1012      1      1 
```
Note that the new output object is considered a regular grid of just 1 grid cell (lon=1, lat=1). This is the default behavior of most functions in `climate4R`, since the packages assumes that most of times we are dealing with gridded datasets. To continue working with a station-like object, the `"loc"` dimension can be recovered again with `redim`:
```R
clt2 <- redim(clt, loc = TRUE)
getShape(clt2)

## member   time    loc 
##    15   1012      1 
```

I hope this helps.

**Comment by dmbettin** [comment]
Great, thank you very much!
